displayName: MTLS or IP Whitelist
type: middleware
iconPath: .assets/icon.jpg

import: github.com/smerschjohann/mtlswhitelist

summary: 'Either allow access based on mTLS or IP Whitelist'

testData:
  allowedCidrs:
  - "192.168.0.0/24"
  - "127.0.0.0/8"
