displayName: MTLS or Whitelist
type: middleware
iconPath: .assets/icon.jpg

import: github.com/smerschjohann/mtlswhitelist

summary: 'Either allow access based on mTLS or IP Whitelist'

testData:
  rules:
  - type: ipRange
    addInterface: true # adds the ip ranges of the default route to the whitelist
    ranges:
    - 127.0.0.1/8
    - 192.168.0.1/16
